In [1]:
import warnings; 
warnings.filterwarnings("ignore")
warnings.simplefilter(action="ignore",category=UserWarning)
warnings.simplefilter(action="ignore",category=FutureWarning)

# Suppress valuewarning when fitting ARIMA model.
from statsmodels.tools.sm_exceptions import ValueWarning
warnings.simplefilter('ignore', ValueWarning)


# Interactive plots embedded within the notebook
#%matplotlib notebook 
# Static images of plots embedded within the notebook
#%matplotlib inline   
%config InlineBackend.figure_formats = {'png', 'retina'}

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from scipy import stats

import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels as sm
import sklearn as skl
from platform import python_version

#pd.options.plotting.backend = "plotly" 
# Conflict with options in original matplotlib.

print('Python version', python_version())
print('Numpy version', np.__version__)
print('Scipy version', sp.__version__)
print('Pandas version', pd.__version__)
print('Matplotlib version', mpl.__version__)
print('Seaborn version', sns.__version__)
print('Statsmodels version', sm.__version__)
###############################################

#plt.style.use('ggplot')
plt.style.use('seaborn-v0_8-muted')
plt.rcParams['figure.figsize'] = (6, 6)
plt.rcParams['grid.linestyle'] = ':'   
plt.rcParams['axes.grid'] = False

sns.set_style("whitegrid", {'axes.grid' : False})
#sns.color_palette("RdBu", n_colors=10)
#sns.color_palette("RdBu_r') # Good for heatmap


Python version 3.12.5
Numpy version 2.0.2
Scipy version 1.14.1
Pandas version 2.2.3
Matplotlib version 3.9.2
Seaborn version 0.13.2
Statsmodels version 0.14.2


# Eigenvalues and Eigenvectors

In [2]:
import numpy as np

np.set_printoptions(suppress=True,precision=4)

A = np.array([[1,-2],[1,4]])
A

array([[ 1, -2],
       [ 1,  4]])

Determine eigenpair of square matrix $A$

In [3]:
egval,egvec = np.linalg.eig(A)
print(egval)
print(egvec)

[2. 3.]
[[-0.8944  0.7071]
 [ 0.4472 -0.7071]]


Determine norms of the eigenvectors

In [4]:
np.linalg.norm(egvec[:,0])
np.linalg.norm(egvec[:,1])

np.float64(0.9999999999999999)

np.float64(0.9999999999999999)

Try 3x3 matrix

In [5]:
A = np.array([[6,-2,-1],[-2,6,-1],[-1,-1,5]])

Determine eigenpair of square matrix $A$ and norms of the eigenvectors

In [6]:
egval,egvec = np.linalg.eig(A)
print(egval)
print(egvec)
np.linalg.norm(egvec[:,0])
np.linalg.norm(egvec[:,1])

[3. 8. 6.]
[[ 0.5774  0.7071 -0.4082]
 [ 0.5774 -0.7071 -0.4082]
 [ 0.5774 -0.      0.8165]]


np.float64(0.9999999999999999)

np.float64(1.0)