In [3]:
import warnings

warnings.filterwarnings("ignore")
warnings.simplefilter(action="ignore",category=UserWarning)
warnings.simplefilter(action="ignore",category=FutureWarning)

# Suppress valuewarning when fitting ARIMA model.
from statsmodels.tools.sm_exceptions import ValueWarning
warnings.simplefilter('ignore', ValueWarning)


# Interactive plots embedded within the notebook
#%matplotlib notebook 
# Static images of plots embedded within the notebook
%config InlineBackend.figure_formats = {'png', 'retina'}

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Support Vector Classifier

## Read input synthetic data

In [4]:
df = pd.read_excel('data/supervised-learning.xlsx', sheet_name='SYNDATA')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      50 non-null     float64
 1   X2      50 non-null     float64
 2   y       50 non-null     int64  
dtypes: float64(2), int64(1)
memory usage: 1.3 KB


## Fit Linear SVC to the train data

In [5]:
X = df.drop('y', axis=1)
X['X2'] = X['X2']*20
y = df[['y']]

In [6]:
from sklearn.svm import LinearSVC

svc_linear = LinearSVC();
svc_linear.fit(X, y);

Evaluate performance on the train data

In [7]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred = svc_linear.predict(X)
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

[[18  7]
 [ 6 19]]
              precision    recall  f1-score   support

          -1       0.75      0.72      0.73        25
           1       0.73      0.76      0.75        25

    accuracy                           0.74        50
   macro avg       0.74      0.74      0.74        50
weighted avg       0.74      0.74      0.74        50



Look at the fitted coefficients

In [8]:
svc_linear.intercept_
svc_linear.coef_

array([-0.41556664])

array([[0.47716399, 0.02038681]])

# <font color='darkorange'>Activity: Linear SVM on Financial data</font>